const ACTION_TYPE = {
  GET_NOTES: "GET_NOTES",
  CREATED_NOTES: "CREATED_NOTES",
  REMOVE_NOTE: "REMOVE_NOTE",
  NOTE_MESSAGE: "NOTE_MESSAGE",
  ADD_TAG: "ADD_TAG",
  ADD_COLOR: "ADD_COLOR",
  ADD_PREFRENCE: "ADD_PREFRENCE",
  UPDATE_SINGLE_NOTE: "UPDATE_SINGLE_NOTE",
  CLEAR: "CLEAR",
};
export { ACTION_TYPE };
